# This is currently needed to check the private ip addresses of the machines
- name: Collect facts from all machines
  hosts: all
  strategy: free
  user: root
  tasks: [ ]
  # This is a special tag which forces this play even with --tags
  tags: [ always ]

- hosts: localhost
  connection: local
  become: false


  # Update all firewall rules except keep the web ports and unique configuration as they were for every machine
  tasks:
    # Prefer populated data from the server
    - name: Remove legacy firewalls for successfully connected machines
      upcloud_firewall:
        state: absent
        ip_address: "{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
        firewall_rules:
          - direction: in
            action: drop
          - direction: out
            action: accept
      with_items:
        - "{{ groups['all'] }}"
      when: hostvars[item]['ansible_eth0'] is defined

    # Fallback for the one in inventory name
    - name: Remove legacy firewalls for all machines in inventory
      upcloud_firewall:
        state: absent
        ip_address: "{{ hostvars[item]['ansible_host']|default(item) }}"
        firewall_rules:
          - direction: in
            action: drop
          - direction: out
            action: accept
      with_items:
        - "{{ groups['all'] }}"
      when: hostvars[item]['ansible_eth0'] is not defined and hostvars[item]['ansible_host'] is defined or item|ipaddr

    - name: Add single firewall rule
      upcloud_firewall:
        state: present
        ip_address: "{{ item }}"
        firewall_rules:
          - direction: 'in'
            source_address_start: 54.200.148.82
            source_address_end: 54.200.148.82
            action: 'accept'
            destination_port_start: 22
            destination_port_end: 22
            protocol: 'tcp'
            family: 'IPv4'
            comment: 'Deploybot server'
      with_items:
        - "{{ groups['all'] }}"

    - name: Block all other connections
      upcloud_firewall:
        state: present
        ip_address: "{{ hostvars[item]['ansible_host']|default(item) }}"
        default_rules:
          - direction: in
            action: drop
          - direction: out
            action: accept
      with_items:
        - "{{ groups['all'] }}"


